name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev automake
          pip3 install --user --upgrade buildozer cython

      - name: Build with Buildozer
        run: |
          # Server ke pre-installed NDK ka path use karo
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/27.3.13750724
          buildozer --verbose android debug
        env:
          PYTHON_VERSION: 3.10

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
